@startuml
UserA -> "Holdable Token": hold(to: UserB)
"Holdable Token" -> Notary: HoldCreated
UserC -> "Holdable Token" : releaseHold
"Holdable Token" -> UserA: release held amount
"Holdable Token" -> UserA: HoldReleased
@enduml
